//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.16 at 04:30:34 PM EET 
//

package entity;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Book", propOrder = { "name", "categories", "country", "year", "authors", "isbn" })
public class Book {

	@XmlElement(name = "Name", required = true)
	protected String name;
	@XmlElement(name = "Categories", required = true)
	protected Categories categories;
	@XmlElement(name = "Country", required = true)
	@XmlSchemaType(name = "string")
	protected String country;
	@XmlElement(name = "Year", required = true)
	protected String year;
	@XmlElement(name = "Authors", required = true)
	protected Authors authors;
	@XmlElement(name = "ISBN", required = true)
	protected String isbn;
	@XmlAttribute(name = "id")
	protected String id;
	protected List<String> author = new ArrayList<>();
	protected List<String> category = new ArrayList<>();

	public Book() {
	}

	public Book(String id, String name, List<String> category, String country, String year, List<String> author,
			String isbn) {
		super();
		this.name = name;
		this.country = country;
		this.year = year;
		this.isbn = isbn;
		this.id = id;
		this.author = author;
		this.category = category;
	}

	public List<String> getListCategories() {
		if (category == null) {
			category = new ArrayList<>();
		}
		return this.category;
	}

	public String getCategory() {
		StringBuilder result = new StringBuilder();
		for (String a : category) {
			result.append(a).append('\n');
		}
		return result.toString();

	}

	public void setCategory(String s) {

		category.add(s);

	}
	
	public void setCategory(List<String> s) {

		category.addAll(s);

	}

	public List<String> getListAuthors() {
		if (author == null) {
			author = new ArrayList<>();
		}
		return this.author;
	}

	public String getAuthor() {
		StringBuilder result = new StringBuilder();
		for (String a : author) {
			result.append(a).append('\n');
		}
		return result.toString();

	}

	public void setAuthor(String s) {

		author.add(s);

	}
	
	public void setAuthor(List<String> s) {

		author.addAll(s);

	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the categories property.
	 * 
	 * @return possible object is {@link Categories }
	 * 
	 */
	public Categories getCategories() {
		return categories;
	}

	/**
	 * Sets the value of the categories property.
	 * 
	 * @param value
	 *            allowed object is {@link Categories }
	 * 
	 */
	public void setCategories(Categories value) {
		this.categories = value;
	}

	/**
	 * Gets the value of the country property.
	 * 
	 * @return possible object is {@link Country }
	 * 
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * Sets the value of the country property.
	 * 
	 * @param value
	 *            allowed object is {@link Country }
	 * 
	 */
	public void setCountry(String value) {
		this.country = value;
	}

	/**
	 * Gets the value of the year property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public String getYear() {
		return year;
	}

	/**
	 * Sets the value of the year property.
	 * 
	 * @param string
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setYear(String string) {
		this.year = string;
	}

	/**
	 * Gets the value of the authors property.
	 * 
	 * @return possible object is {@link Authors }
	 * 
	 */
	public Authors getAuthors() {
		return authors;
	}

	/**
	 * Sets the value of the authors property.
	 * 
	 * @param value
	 *            allowed object is {@link Authors }
	 * 
	 */
	public void setAuthors(Authors value) {
		this.authors = value;
	}

	/**
	 * Gets the value of the isbn property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public String getISBN() {
		return isbn;
	}

	/**
	 * Sets the value of the isbn property.
	 * 
	 * @param string
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setISBN(String string) {
		this.isbn = string;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link Long }
	 * 
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param sent
	 *            allowed object is {@link Long }
	 * 
	 */
	public void setId(String sent) {
		this.id = sent;
	}

	@Override
	public String toString() {
		return "Name: " + name + "|| Country: " + country + "|| Year:" + year + "|| ISBN: " + isbn + ", ID: " + id
				+ "|| Author: " + author + "|| Category:" + category + "\n";
	}

}
