//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.16 at 04:30:34 PM EET 
//


package entity;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


@XmlType(name = "category")
@XmlEnum
public enum Category {

    @XmlEnumValue("historical")
    HISTORICAL("historical"),
    @XmlEnumValue("authobiography")
    AUTHOBIOGRAPHY("authobiography"),
    @XmlEnumValue("fiction")
    FICTION("fiction"),
    @XmlEnumValue("novel")
    NOVEL("novel");
    private final String value;

    Category(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Category fromValue(String v) {
        for (Category c: Category.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
