//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.16 at 04:30:34 PM EET 
//


package entity;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


@XmlType(name = "Country")
@XmlEnum
public enum Country {

    USA("USA"),
    @XmlEnumValue("France")
    FRANCE("France"),
    @XmlEnumValue("Russia")
    RUSSIA("Russia"),
    @XmlEnumValue("German")
    GERMAN("German"),
    @XmlEnumValue("Italia")
    ITALIA("Italia"),
    @XmlEnumValue("India")
    INDIA("India"),
    @XmlEnumValue("England")
    ENGLAND("England");
    private final String value;

    Country(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Country fromValue(String v) {
        for (Country c: Country.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
